config/routes.rb
Rails.application.routes.draw do
  resources :invoices, only: %i[index show destroy] do
    collection do
      post :import
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "invoices#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/facturx_json_concern.rb
# all the methods related to factur-x documents are defined here
# rubocop:disable Layout/LineLength
module FacturxJsonConcern
  extend ActiveSupport::Concern

  def xml_document_to_json
    return '' if xml_document.nil?

    parser = Nori.new
    hash = parser.parse(xml_document)
    hash.to_json
    JSON.parse(hash.to_json)
  end

  # sum total
  def due_payable_amount
    xml_document_to_json.dig('rsm:CrossIndustryInvoice', 'rsm:SupplyChainTradeTransaction', 'ram:ApplicableHeaderTradeSettlement', 'ram:SpecifiedTradeSettlementHeaderMonetarySummation', 'ram:DuePayableAmount')
  end

  def invoice_currency_code
    xml_document_to_json.dig('rsm:CrossIndustryInvoice', 'rsm:SupplyChainTradeTransaction', 'ram:ApplicableHeaderTradeSettlement', 'ram:InvoiceCurrencyCode')
  end

  def invoice_date
    DateTime.parse xml_document_to_json.dig('rsm:CrossIndustryInvoice', 'rsm:ExchangedDocument', 'ram:IssueDateTime', 'udt:DateTimeString')
  end

  def invoice_number
    xml_document_to_json.dig('rsm:CrossIndustryInvoice', 'rsm:ExchangedDocument', 'ram:ID')
  end

  def sender
    { name: xml_document_to_json.dig('rsm:CrossIndustryInvoice', 'rsm:SupplyChainTradeTransaction', 'ram:ApplicableHeaderTradeAgreement', 'ram:SellerTradeParty', 'ram:Name'),
      vat: sender_vat }
  end

  def recipient
    { name: xml_document_to_json.dig('rsm:CrossIndustryInvoice', 'rsm:SupplyChainTradeTransaction', 'ram:ApplicableHeaderTradeAgreement', 'ram:BuyerTradeParty', 'ram:Name'),
      vat: xml_document_to_json.dig('rsm:CrossIndustryInvoice', 'rsm:SupplyChainTradeTransaction', 'ram:ApplicableHeaderTradeAgreement', 'ram:BuyerTradeParty', 'ram:SpecifiedTaxRegistration', 'ram:ID') }
  end

  def line_items
    xml_document_to_json.dig('rsm:CrossIndustryInvoice', 'rsm:SupplyChainTradeTransaction', 'ram:IncludedSupplyChainTradeLineItem')
  end

  # "sub-sums" (the totals for each tax-type (0%, 7% and 19%))
  def tax_totals
    line_items = xml_document_to_json.dig('rsm:CrossIndustryInvoice', 'rsm:SupplyChainTradeTransaction', 'ram:IncludedSupplyChainTradeLineItem')
    totals = Hash.new(0)
    line_items.each do |item|
      tax_rate = item.dig('ram:SpecifiedLineTradeSettlement', 'ram:ApplicableTradeTax', 'ram:RateApplicablePercent').to_f
      total_amount = item.dig('ram:SpecifiedLineTradeSettlement', 'ram:SpecifiedTradeSettlementLineMonetarySummation', 'ram:LineTotalAmount').to_f
      totals[tax_rate] += total_amount
    end
    totals
  end

  private

  # [{"ram:ID"=>"201/113/40209"}, {"ram:ID"=>"DE123456789"}]
  def sender_vat
    result = xml_document_to_json.dig('rsm:CrossIndustryInvoice', 'rsm:SupplyChainTradeTransaction', 'ram:ApplicableHeaderTradeAgreement', 'ram:SellerTradeParty', 'ram:SpecifiedTaxRegistration')

    vat = if result.is_a?(Array)
      result.map { |item| item['ram:ID'] }
    else
      result['ram:ID']
    end
  end
end
# rubocop:enable Layout/LineLength

app/models/concerns/facturx_xml_concern.rb
# all the methods related to factur-x documents are defined here
module FacturxXmlConcern
  extend ActiveSupport::Concern

  def parsed_xml
    Nokogiri::XML(xml_document)
  end

  def iban
    parsed_xml.xpath('//ram:IBANID').text
  end

  def account_name
    parsed_xml.xpath('//ram:AccountName').text
  end
end

app/models/concerns/xml_document_concern.rb
# all the methods related to factur-x documents are defined here
module XmlDocumentConcern
  extend ActiveSupport::Concern

  def xml_document_to_json
    return '' if xml_document.nil?

    parser = Nori.new
    hash = parser.parse(xml_document)
    hash.to_json
    JSON.parse(hash.to_json)
  end

  def due_payable_amount
    xml_document_to_json.dig('rsm:CrossIndustryInvoice', 'rsm:SupplyChainTradeTransaction', 'ram:ApplicableHeaderTradeSettlement', 'ram:SpecifiedTradeSettlementHeaderMonetarySummation', 'ram:DuePayableAmount')
  end
end

app/models/invoice.rb
# xml_document: :text
# xml_valid: :boolean
class Invoice < ApplicationRecord
  include FacturxJsonConcern
  include FacturxXmlConcern

  has_one_attached :pdf_document

  after_create_commit :extract_xml

  def pretty_xml
    Nokogiri::XML(xml_document).to_xml(indent: 2)
  end

  private

  def extract_xml
    if xml_document.present?
      validate_xml
    elsif pdf_document.attached? && pdf_document.blob.content_type == 'application/pdf'
      PdfBlobToXmlJob.perform_now(self)
    end
  end

  def validate_xml
    # assumes that the xml is valid if the invoice number is present
    # alternative would be to use an XML schema validation tool
    update(xml_valid: invoice_number.present?)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def index
    @invoices = Invoice.order(created_at: :desc)
  end

  def import
    files = params[:files]
    files = files.compact_blank
    files.each do |file|
      case file.content_type
      when 'application/pdf'
        Invoice.create(pdf_document: file)
      when 'text/xml', 'application/xml'
        Invoice.create(xml_document: File.read(file))
      end
    end

    redirect_to invoices_url, notice: 'Invoices imported.'
  end

  def show
    @invoice = Invoice.find(params[:id])
  end

  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy

    redirect_to invoices_url, notice: 'Invoice deleted.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def boolean_label(boolean)
    boolean ? '✅' : '❌'
  end
end

app/views/invoices/_import.html.erb
<%= form_with url: import_invoices_path, method: :post do |form| %>
  <%= form.file_field :files, multiple: true, accept: 'application/pdf,application/xml' %>
  <%= form.submit 'Import' %>
<% end %>

app/views/invoices/_invoice.html.erb
<div id="<%= dom_id invoice %>" style="border: 1px solid #ccc; padding: 10px; margin: 10px 0;">
  <%= link_to invoice.id, invoice_path(invoice) %>
  <p>
    <strong>File attached:</strong>
    <% if invoice.pdf_document.attached? %>
      <%= link_to rails_blob_path(invoice.pdf_document, disposition: "inline"), target: :_blank do %>
        <% if invoice.pdf_document.representable? %>
          <%= image_tag invoice.pdf_document.representation(resize_to_limit: [200, 200]) %>
        <% end %>
        <br>
        <%= invoice.pdf_document.blob.filename %>
        <%= number_to_human_size invoice.pdf_document.blob.byte_size %>
      <% end %>
    <% else %>
      No attachments
    <% end %>
  </p>

  <p>
    <strong>Valid FacturX:</strong>
    <%= boolean_label(invoice.xml_valid) %>
  </p>

  <p>
    <strong>Invoice attributes:</strong>
    <% if invoice.xml_document.present? %>
      <br>
      invoice_number:
      <%= invoice.invoice_number %>
      <br>
      invoice_date:
      <%= invoice.invoice_date %>
      <br>
      due_payable_amount:
      <%= invoice.due_payable_amount %>
      <br>
      invoice_currency_code:
      <%= invoice.invoice_currency_code %>
      <br>
      sender:
      <%= invoice.sender %>
      <br>
      recipient:
      <%= invoice.recipient %>
    <% end %>
  </p>

  <%= button_to 'Delete', invoice, method: :delete, data: { turbo_confirm: "Are you sure?" } %>
</div>

app/views/invoices/index.html.erb
<h1>Import</h1>

<%= render 'import' %>

<h1>
  Invoices:
  <%= @invoices.count %>
</h1>

<div id="invoices">
  <% @invoices.each do |invoice| %>
    <%= render invoice %>
  <% end %>
</div>

app/views/invoices/show.html.erb
<%= render @invoice %>

<pre><code>
  <%= @invoice.pretty_xml %>
</code></pre>

<%#= @invoice.xml_document %>
<%#= @invoice.xml_document_to_json %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacturX Reader</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
      <p style="color: green"><%= notice %></p>
    <% end %>
    <%= link_to_unless_current 'Invoices', invoices_path %>
    <hr>
    <%= yield %>
  </body>
</html>